---

- name: install prerequisites
  become_user: root
  # See https://www.mediawiki.org/wiki/Manual:Installation_requirements
  apt:
    name: "{{ item }}"
    #update_cache: yes # commented out for dev purposes
    state: present
  loop:
    - pipenv

- name: Setup installation directory
  file:
    path: "{{ torquedata_install_directory }}"
    state: directory

- name: Checkout Torque
  git:
    repo: https://github.com/OpenTechStrategies/torque
    dest: "{{ torquedata_install_directory }}/torque/"
    version: cec50c3

- name: Link TorqueData
  file:
    src: "{{ torquedata_install_directory }}/torque/torquedata/"
    dest: "{{ torquedata_install_directory }}/server"
    state: link

- name: Install torquedata supervisor
  become_user: root
  template:
    src: supervisor-torquedata.conf.j2
    dest: /etc/supervisor/conf.d/torquedata.conf

- name: Run pipenv install
  command: "pipenv install"
  args:
    chdir: "{{ torquedata_install_directory }}/server"

- name: Install torquedata configuration
  template:
    src: config.py.j2
    dest: "{{ torquedata_install_directory }}/server/config.py"

- name: Create Spreadsheet Directory
  file:
    state: directory
    path: "{{ torquedata_install_directory }}/spreadsheets"

- name: Restart supervisor for torquedata
  become_user: root
  supervisorctl:
    name: 'torquedata'
    state: restarted
