- name: install prerequisites
  become_user: root
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    # These are MariaDB in Debian, and Oracle's MySQL in Ubuntu
    - default-mysql-server
    - default-mysql-client
    - python-mysqldb # This is needed for ansible

- name: Create database user
  become_user: root
  mysql_user:
    login_password: "{{ mysql_root_password }}"
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    state: present
    priv: "{{ competition_name }}.*:ALL"
    append_privs: yes
